export enum userTypes {
  USER_AUTH_REQUEST = 'USER_AUTH_REQUEST',
  USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS',
  USER_AUTH_FAILURE = 'USER_AUTH_FAILURE',
  USER_CHECK = 'USER_CHECK',
  USER_LOGOUT = 'USER_LOGOUT',
}
