export enum userTypes {
  USER_AUTH_REQUEST = 'USER_AUTH_REQUEST',
  USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS',
  USER_AUTH_FAILURE = 'USER_AUTH_FAILURE',
  USER_CHECK = 'USER_CHECK',
  USER_LOGOUT = 'USER_LOGOUT',
}

export enum consoleTypes {
  CONSOLE_SIZE = 'CONSOLE_SIZE',
  CONSOLE_CHANGE = 'CONSOLE_CHANGE',
  CONSOLE_FORMAT = 'CONSOLE_FORMAT',
  CONSOLE_REQUEST = 'CONSOLE_REQUEST',
  CONSOLE_SUCCESS = 'CONSOLE_SUCCESS',
  CONSOLE_FAILURE = 'CONSOLE_FAILURE',
  CONSOLE_HISTORY_CLEAR = 'CONSOLE_HISTORY_CLEAR',
}
